# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('teams', '0001_initial'), ('teams', '0002_auto_20170425_1029'), ('teams', '0003_auto_20170425_1400'), ('teams', '0004_userprofile_seat_squashed'), ('teams', '0005_auto_20170802_2230'), ('teams', '0004_auto_20170721_1807'), ('teams', '0006_merge_20170802_2329')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('at_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('seat', models.CharField(blank=True, default='', help_text='Enter your seat so we can find you easily if you get stuck. (To help you, not to mock you <3)', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='team_invites', to='teams.UserProfile'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.UserProfile'),
        ),
        migrations.AddField(
            model_name='team',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='team_requests', to='teams.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name', 'at_event')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([]),
        ),
    ]
