# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hunts', '0001_squashed_0060_auto_20180410_2136'),
        ('teams', '0001_squashed_0006_merge_20170802_2329'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.RemoveField(
                model_name='team',
                name='invites',
            ),
            migrations.RemoveField(
                model_name='team',
                name='members',
            ),
            migrations.RemoveField(
                model_name='team',
                name='requests',
            ),
            migrations.DeleteModel(
                name='UserProfile',
            ),
        ]),
    ]
