# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170425_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='team_invites', to='teams.UserProfile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.UserProfile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='team_requests', to='teams.UserProfile'),
        ),
    ]
