# Generated by Django 2.2.4 on 2019-09-22 20:25

from django.db import migrations
import enumfields.fields
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180513_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='role',
            field=enumfields.fields.EnumField(default='p', enum=teams.models.TeamRole, help_text='Role of the team. Admins can edit the event and see admin views, authors are credited on the about page', max_length=1),
        ),
    ]
