# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('teams', '0004_userprofile_seat'), ('teams', '0005_auto_20170801_2322')]

    dependencies = [
        ('teams', '0003_auto_20170425_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seat',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
