# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20170425_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seat',
            field=models.CharField(blank=True, default='', help_text='Enter your seat so we can find you easily if you get stuck. (To help you, not to mock you <3)', max_length=6)
        ),
    ]
