# Generated by Django 2.2.4 on 2019-09-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190922_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_admin',
        ),
    ]
