# Generated by Django 3.1.5 on 2021-01-24 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
