# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20170802_2230'),
        ('teams', '0004_auto_20170721_1807'),
    ]

    operations = [
    ]
