# Generated by Django 3.1.5 on 2021-01-24 23:27

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    for row in Team.objects.all():
        row.token = uuid.uuid4()
        row.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(
            code=gen_uuid,
        ),
    ]
