# Generated by Django 3.1.5 on 2021-01-26 23:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
