# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 16:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170715_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.IntegerField(default=0, help_text='Maximum size for a team at this event, or 0 for no limit.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
