# Generated by Django 2.1.4 on 2019-01-10 23:23

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180703_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(help_text='The extension of the uploaded file will determine the Content-Type of the file when served', upload_to=events.models.event_file_path),
        ),
    ]
