# Generated by Django 2.1.4 on 2019-01-04 19:30

from django.db import migrations, models
import django.db.models.deletion


def populate_userinfo(apps, schema_editor):
    Attendance = apps.get_model('events', 'Attendance')
    UserInfo = apps.get_model('accounts', 'UserInfo')
    for attendance in Attendance.objects.all():
        attendance.user_info, _ = UserInfo.objects.get_or_create(user=attendance.user.user)
        attendance.save()


def populate_userprofile(apps, schema_editor):
    Attendance = apps.get_model('events', 'Attendance')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for attendance in Attendance.objects.all():
        attendance.user, _ = UserProfile.objects.get_or_create(user=attendance.user_info.user)
        attendance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinfo'),
        ('events', '0005_auto_20180703_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user'), ('event', 'user_info')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
        migrations.RunPython(
            code=populate_userinfo,
            reverse_code=populate_userprofile,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user_info')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
