# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 21:36
from __future__ import unicode_literals

import re
from django.db import migrations, models
import events.models


def migrate_event_files(apps, schema_editor):
    EventFile = apps.get_model('events', 'EventFile')
    for event_file in EventFile.objects.all():
        event_file.file = re.sub(r"^puzzles/", "puzzles/{0}/".format(event_file.puzzle.id), str(event_file.file))
        event_file.save()


def revert_event_files(apps, schema_editor):
    EventFile = apps.get_model('events', 'EventFile')
    for event_file in EventFile.objects.all():
        event_file.file = re.sub(r"^puzzles/\d+/", "puzzles/", str(event_file.file))
        event_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170810_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to=events.models.event_file_path),
        ),
        migrations.RunPython(migrate_event_files, reverse_code=revert_event_files),
    ]
