# Generated by Django 2.1.5 on 2019-01-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190110_2323'),
        ('events', '0006_auto_20190104_1930'),
    ]

    operations = [
    ]
