# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:41
from __future__ import unicode_literals

from django.db import migrations
import os
import shutil


def migrate_event_files(apps, schema_editor):
    EventFile = apps.get_model('events', 'EventFile')
    for event_file in EventFile.objects.all():
        old_file = os.path.join('/uploads/events', os.path.basename(event_file.file.path))
        try:
            shutil.move(old_file, event_file.file.path)
        except FileNotFoundError:
            pass

def revert_event_files(apps, schema_editor):
    EventFile = apps.get_model('events', 'EventFile')
    for event_file in EventFile.objects.all():
        old_file = os.path.join('/uploads/events', os.path.basename(event_file.file.path))
        try:
            shutil.move(event_file.file.path, old_file)
        except FileNotFoundError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170813_2236'),
    ]

    operations = [
        migrations.RunPython(migrate_event_files, reverse_code=revert_event_files),
    ]
