# Generated by Django 2.2 on 2019-04-09 09:09

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_merge_20190124_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
