# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170814_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='help_text',
            field=models.TextField(default='', help_text='Content for the event help page'),
            preserve_default=False,
        ),
    ]
