# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='examples_text',
            field=models.TextField(default='', help_text='Content for the example puzzles for this event'),
            preserve_default=False,
        ),
    ]
