# Generated by Django 3.1.5 on 2021-01-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_seat_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discord_bot_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='discord_url',
            field=models.URLField(blank=True),
        ),
    ]
