# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_examples_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about_text',
            field=models.TextField(blank=True, help_text='Content for the event about page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='examples_text',
            field=models.TextField(blank=True, help_text='Content for the example puzzles for this event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='help_text',
            field=models.TextField(blank=True, help_text='Content for the event help page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules_text',
            field=models.TextField(blank=True, help_text='Content for the event rules page'),
        ),
    ]
