# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180408_1252'),
        ('events', '0011_auto_20180411_1536'),
    ]

    operations = [
    ]
