# Generated by Django 3.1.5 on 2021-01-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter2', '0002_auto_20200718_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
    ]
