# Generated by Django 3.1.5 on 2021-01-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter2', '0003_configuration_privacy_policy'),
        ('hunter2', '0003_file_icon'),
    ]

    operations = [
    ]
