# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hunts', '0001_squashed_0060_auto_20180410_2136'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterField(
                model_name='guess',
                name='by',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
            ),
            migrations.AlterField(
                model_name='userdata',
                name='user',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
            ),
            migrations.AlterField(
                model_name='userpuzzledata',
                name='user',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
            ),
        ]),
    ]
