# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_auto_20180513_1909'),
        ('hunts', '0002_auto_20180514_2037'),
    ]

    operations = [
    ]
