# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_blank_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
