# Generated by Django 2.0.7 on 2018-07-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0003_merge_20180603_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='runtime',
            field=models.CharField(choices=[('r', 'Case Sensitive Regex Runtime'), ('s', 'Case Sensitive Static Runtime'), ('I', 'IFrame Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime'), ('S', 'Static Runtime')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('r', 'Case Sensitive Regex Runtime'), ('s', 'Case Sensitive Static Runtime'), ('I', 'IFrame Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime'), ('S', 'Static Runtime')], default='S', help_text='Runtime for responding to an AJAX callback for this question, should return JSON', max_length=1, verbose_name='Callback runtime'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('r', 'Case Sensitive Regex Runtime'), ('s', 'Case Sensitive Static Runtime'), ('I', 'IFrame Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime'), ('S', 'Static Runtime')], default='S', help_text='Runtime for generating the question content', max_length=1),
        ),
        migrations.AlterField(
            model_name='unlockanswer',
            name='runtime',
            field=models.CharField(choices=[('r', 'Case Sensitive Regex Runtime'), ('s', 'Case Sensitive Static Runtime'), ('I', 'IFrame Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime'), ('S', 'Static Runtime')], default='S', max_length=1),
        ),
    ]
