# Generated by Django 2.1.7 on 2019-04-08 20:43

from django.db import migrations, models
import hunts.models

def gen_url_ids(apps, schema_editor):
    for pz in hunts.models.Puzzle.objects.all():
        pz.url_id = hunts.models.generate_url_id()
        pz.save(update_fields=['url_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0003_auto_20190307_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='url_id',
            field=models.CharField(editable=False, max_length=8, blank=True, null=True),
        ),
        migrations.RunPython(gen_url_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='puzzle',
            name='url_id',
            field=models.CharField(default=hunts.models.generate_url_id, editable=False, max_length=8, unique=True),
        )
    ]
