# Generated by Django 2.2 on 2019-08-11 15:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_puzzle_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='start_after',
            field=models.ForeignKey(blank=True, help_text='If you select an unlock here, the time will start counting from when that is unlocked.', null=True, on_delete=django.db.models.deletion.CASCADE, to='hunts.Unlock', verbose_name='Start after Unlock'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='time',
            field=models.DurationField(help_text='Time after anyone on the team first loads the puzzle or (if set) unlocks the related unlock to display this hint', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Delay'),
        ),
    ]
