# Generated by Django 2.2 on 2019-05-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_puzzle_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='start_after',
            field=models.ForeignKey(help_text='If you select an unlock here, the time will start counting from when that is unlocked.', null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='hunts.Unlock', verbose_name='Start after Unlock'),
        ),
    ]
