# Generated by Django 2.0.7 on 2018-07-31 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_auto_20180716_2132'),
        ('hunts', '0004_auto_20180702_0750'),
    ]

    operations = [
    ]
