# Generated by Django 3.0.2 on 2020-04-05 20:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_auto_20190811_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="Options for configuring the validator in JSON format using the following keys:\n\nStatic:\n    'case_handling': [Default: lower]\n        'none' - do not adjust case\n        'lower' - compare lower case\n        'fold' - perform unicode case folding\n    'strip': true/false [Default: true]\n\nRegex:\n    'case_sensitive': true/false [Default: false]", verbose_name='Validator configuration'),
        ),
        migrations.AlterField(
            model_name='unlockanswer',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="Options for configuring the validator in JSON format using the following keys:\n\nStatic:\n    'case_handling': [Default: lower]\n        'none' - do not adjust case\n        'lower' - compare lower case\n        'fold' - perform unicode case folding\n    'strip': true/false [Default: true]\n\nRegex:\n    'case_sensitive': true/false [Default: false]", verbose_name='Validator configuration'),
        ),
    ]
