# Generated by Django 2.0.7 on 2018-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_merge_20180731_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='soln_runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('s', 'Case Sensitive Static Runtime'), ('R', 'Regex Runtime'), ('r', 'Case Sensitive Regex Runtime'), ('I', 'IFrame Runtime'), ('L', 'Lua Runtime')], default='S', help_text='Runtime for generating the question solution', max_length=1, verbose_name='Solution runtime'),
        ),
    ]
