# Generated by Django 2.2 on 2019-06-08 19:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_hint_start_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='time',
            field=models.DurationField(help_text='Time after anyone on the team first loads the puzzle to display this hint', validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1))], verbose_name='Delay'),
        ),
    ]
