# Generated by Django 3.1.3 on 2020-11-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0006_auto_20200405_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text="Options for configuring the validator in JSON format using the following keys:\n\nStatic:\n    'case_handling': [Default: lower]\n        'none' - do not adjust case\n        'lower' - compare lower case\n        'fold' - perform unicode case folding\n    'strip': true/false [Default: true]\n\nRegex:\n    'case_sensitive': true/false [Default: false]", verbose_name='Validator configuration'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_options',
            field=models.JSONField(blank=True, default=dict, help_text='Options for configuring the AJAX callback processor in JSON format. Currently no options are supported.', verbose_name='AJAX callback processor configuration'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Options for configuring the puzzle page renderer in JSON format. Currently no options are supported.', verbose_name='Puzzle page renderer configuration'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='soln_options',
            field=models.JSONField(blank=True, default=dict, help_text='Options for configuring the solution renderer in JSON format. Currently no options are supported.', verbose_name='Solution renderer configuration'),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teampuzzledata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unlockanswer',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text="Options for configuring the validator in JSON format using the following keys:\n\nStatic:\n    'case_handling': [Default: lower]\n        'none' - do not adjust case\n        'lower' - compare lower case\n        'fold' - perform unicode case folding\n    'strip': true/false [Default: true]\n\nRegex:\n    'case_sensitive': true/false [Default: false]", verbose_name='Validator configuration'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpuzzledata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
