# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('hunts', '0007_auto_20170108_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='events.Event')),
                ('puzzles', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='hunts.Puzzle')),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzleset',
            name='event',
        ),
        migrations.RemoveField(
            model_name='puzzleset',
            name='puzzles',
        ),
        migrations.DeleteModel(
            name='PuzzleSet',
        ),
    ]
