# Generated by Django 2.0.7 on 2018-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0007_auto_20180812_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlefile',
            name='slug',
            field=models.CharField(blank=True, help_text='Include the URL of the file in puzzle content using $slug or ${slug}.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='slug',
            field=models.CharField(blank=True, help_text='Include the URL of the file in solution content using $slug or ${slug}.', max_length=50, null=True),
        ),
    ]
