# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 23:35
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('hunts', '0009_episode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='puzzles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='episodes', to='hunts.Puzzle'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set([('event', 'start_date')]),
        ),
    ]
