# Generated by Django 2.1.2 on 2018-12-16 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0009_episode_winning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date/Time for puzzle to start. Only applies if the puzzle is part of a parallel episode.'),
        ),
    ]
