# Generated by Django 2.1.2 on 2018-12-26 19:19

import uuid

from django.db import migrations, models


def match(apps, schema_editor):
    UnlockAnswer = apps.get_model('hunts', 'UnlockAnswer')
    Unlock = apps.get_model('hunts', 'Unlock')
    for unlock_answer in UnlockAnswer.objects.all():
        unlock_answer.temp_unlock = Unlock.objects.get(old_id=unlock_answer.unlock).id
        unlock_answer.save()


def gen_uuid(apps, schema_editor):
    for model in ('Hint', 'Unlock'):
        Model = apps.get_model('hunts', model)
        for row in Model.objects.all():
            row.id = uuid.uuid4()
            row.save(update_fields=['id'])


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0009_episode_winning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockanswer',
            name='unlock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unlock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='hint',
            old_name='id',
            new_name='old_id',
        ),
        migrations.RenameField(
            model_name='unlock',
            old_name='id',
            new_name='old_id',
        ),
        migrations.AddField(
            model_name='hint',
            name='id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='unlock',
            name='id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(
            code=gen_uuid,
        ),
        migrations.AlterField(
            model_name='hint',
            name='old_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unlock',
            name='old_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='unlock',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='UnlockAnswer',
            name='temp_unlock',
            field=models.UUIDField(null=True)
        ),
        migrations.RunPython(
            code=match
        ),
        migrations.RemoveField(
            model_name='UnlockAnswer',
            name='unlock'
        ),
        migrations.RenameField(
            model_name='UnlockAnswer',
            old_name='temp_unlock',
            new_name='unlock'
        ),
        migrations.AlterField(
            model_name='UnlockAnswer',
            name='unlock',
            field=models.ForeignKey(on_delete=models.CASCADE, to='Unlock')
        ),
        migrations.RemoveField(
            model_name='hint',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='unlock',
            name='old_id',
        ),
    ]
