# Generated by Django 2.1.2 on 2018-12-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0010_auto_20181216_1734'),
        ('hunts', '0010_auto_20181226_1919'),
    ]

    operations = [
    ]
