# Generated by Django 2.1.2 on 2018-12-29 20:11

from django.db import migrations
from django.db.models import Count


def merge_clues(apps, schema_editor):
    Hint = apps.get_model('hunts', 'Hint')
    for dupe in Hint.objects.values('puzzle', 'text').annotate(Count('id')).order_by().filter(id__count__gt=1):
        to_delete = Hint.objects.filter(puzzle=dupe['puzzle'], text=dupe['text']).order_by('time')[1:]
        Hint.objects.filter(pk__in=to_delete).delete()

    Unlock = apps.get_model('hunts', 'Unlock')
    UnlockAnswer = apps.get_model('hunts', 'UnlockAnswer')
    for dupe in Unlock.objects.values('puzzle', 'text').annotate(Count('id')).order_by().filter(id__count__gt=1):
        unlocks = Unlock.objects.filter(puzzle=dupe['puzzle'], text=dupe['text'])
        to_merge = unlocks[1:]
        UnlockAnswer.objects.filter(unlock__in=to_merge).update(unlock=unlocks.first())
        Unlock.objects.filter(pk__in=to_merge).delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0010_auto_20181226_1919'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[ 
                migrations.RunPython(
                    code=merge_clues,
                    reverse_code=do_nothing,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='hint',
                    unique_together={('puzzle', 'text')},
                ),
                migrations.AlterUniqueTogether(
                    name='unlock',
                    unique_together={('puzzle', 'text')},
                ),
            ],
        ),
    ]
