# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0010_auto_20170115_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime')], default='S', max_length=1),
        ),
    ]
