# Generated by Django 2.1.4 on 2019-01-08 08:40

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Model = apps.get_model('hunts', 'guess')
    for row in Model.objects.all():
        row.id = uuid.uuid4()
        row.save(update_fields=['id'])


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_merge_20181228_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='guess',
            old_name='id',
            new_name='old_id',
        ),
        migrations.AddField(
            model_name='guess',
            name='id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(
            code=gen_uuid,
        ),
        migrations.AlterField(
            model_name='guess',
            name='old_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='guess',
            name='old_id',
        ),
    ]
