# Generated by Django 2.1.4 on 2019-01-10 23:23

from django.db import migrations, models
import hunts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_merge_20181228_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua')], default='S', help_text='Processor to use to check whether guess is correct', max_length=1, verbose_name='Validator'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='time',
            field=models.DurationField(help_text='Time after anyone on the team first loads the puzzle to display this hint', verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_content',
            field=models.TextField(blank=True, default='', help_text='Script for generating AJAX responses for callbacks made by puzzle', verbose_name='AJAX callback script'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua')], default='S', help_text='Processor used to execute the callback script in response to AJAX requests', max_length=1, verbose_name='AJAX callback processor'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='content',
            field=models.TextField(help_text='Main puzzle page content, generated using the puzzle renderer', verbose_name='Puzzle page content'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua')], default='S', help_text='Renderer for generating the main puzzle page', max_length=1, verbose_name='Puzzle page renderer'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='soln_content',
            field=models.TextField(blank=True, default='', help_text='Content to be displayed to all users on the puzzle page after the event has completed', verbose_name='Solution content'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='soln_runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua')], default='S', help_text='Renderer for generating the question solution', max_length=1, verbose_name='Solution renderer'),
        ),
        migrations.AlterField(
            model_name='puzzlefile',
            name='file',
            field=models.FileField(help_text='The extension of the uploaded file will determine the Content-Type of the file when served', upload_to=hunts.models.puzzle_file_path),
        ),
        migrations.AlterField(
            model_name='puzzlefile',
            name='slug',
            field=models.CharField(blank=True, help_text='Include the URL of the file in puzzle content using $slug or ${slug}.', max_length=50, null=True, verbose_name='Template Slug'),
        ),
        migrations.AlterField(
            model_name='puzzlefile',
            name='url_path',
            field=models.CharField(help_text='The file path you want to appear in the URL. Can include "directories" using /', max_length=50, verbose_name='URL Filename'),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='file',
            field=models.FileField(help_text='The extension of the uploaded file will determine the Content-Type of the file when served', upload_to=hunts.models.solution_file_path),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='slug',
            field=models.CharField(blank=True, help_text='Include the URL of the file in puzzle content using $slug or ${slug}.', max_length=50, null=True, verbose_name='Template Slug'),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='url_path',
            field=models.CharField(help_text='The file path you want to appear in the URL. Can include "directories" using /', max_length=50, verbose_name='URL Filename'),
        ),
        migrations.AlterField(
            model_name='unlockanswer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static'), ('s', 'Case Sensitive Static'), ('R', 'Regex'), ('r', 'Case Sensitive Regex'), ('I', 'IFrame'), ('L', 'Lua')], default='S', help_text='Processor to use to check whether guess unlocks this unlock', max_length=1, verbose_name='Validator'),
        ),
    ]
