# Generated by Django 2.1.4 on 2019-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_merge_20181228_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='time',
            field=models.DurationField(help_text='Time after anyone on the team first loads the puzzle to display this hint'),
        ),
    ]
