# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_puzzle_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
