# Generated by Django 2.1.4 on 2019-01-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0011_auto_20181229_2011'),
        ('hunts', '0011_merge_20181228_1219'),
    ]

    operations = [
    ]
