# Generated by Django 2.1.5 on 2019-01-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0012_auto_20190110_2323'),
        ('hunts', '0012_merge_20190101_1431'),
    ]

    operations = [
    ]
