# Generated by Django 2.1.4 on 2019-01-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0012_auto_20190108_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockanswer',
            name='unlock',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='hunts.Unlock'),
        ),
    ]
