# Generated by Django 2.1.4 on 2019-01-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0013_auto_20190108_0937'),
        ('hunts', '0012_merge_20190101_1431'),
    ]

    operations = [
    ]
