# Generated by Django 2.1.5 on 2019-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0013_merge_20190124_2043'),
        ('hunts', '0014_merge_20190111_0921'),
    ]

    operations = [
    ]
