# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0015_auto_20170226_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampuzzledata',
            options={'verbose_name_plural': 'Team puzzle data'},
        ),
        migrations.AlterModelOptions(
            name='userpuzzledata',
            options={'verbose_name_plural': 'User puzzle data'},
        ),
        migrations.AddField(
            model_name='puzzle',
            name='cb_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='teampuzzledata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='teampuzzledata',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamdata', to='hunts.Puzzle'),
        ),
        migrations.AlterField(
            model_name='userpuzzledata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='userpuzzledata',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='hunts.Puzzle'),
        ),
    ]
