# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0016_auto_20170227_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='cb_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
