# Generated by Django 2.1.5 on 2019-02-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0016_auto_20190207_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('start_date',)},
        ),
        migrations.AlterModelOptions(
            name='puzzle',
            options={'ordering': ('episode', 'order')},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='puzzles',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.Episode'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
