# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0017_auto_20170227_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime')], default='S', max_length=1),
        ),
    ]
