# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0018_auto_20170308_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockguess',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(),
        ),
    ]
