# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0020_teamdata_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='for_puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.Puzzle'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='puzzles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='hunts.Puzzle'),
        ),
        migrations.AlterField(
            model_name='teampuzzledata',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.Puzzle'),
        ),
        migrations.AlterField(
            model_name='unlockguess',
            name='unlock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.Unlock'),
        ),
        migrations.AlterField(
            model_name='userpuzzledata',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.Puzzle'),
        ),
    ]
