# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0022_puzzlefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlefile',
            name='file',
            field=models.FileField(upload_to='puzzles/'),
        ),
    ]
