# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0022_puzzlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampuzzledata',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
