# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0023_teampuzzledata_start_time'),
        ('hunts', '0023_auto_20170328_1855'),
    ]

    operations = [
    ]
