# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0024_merge_20170328_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Run')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Run')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Run')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='unlockguess',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Run')], default='S', max_length=1),
        ),
    ]
