# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0025_auto_20170424_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='parallel',
            field=models.BooleanField(default=False),
        ),
    ]
