# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0026_auto_20170718_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpuzzledata',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
