# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0026_episode_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
