# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0027_puzzle_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='headstart_granted',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
