# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 00:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0028_puzzle_headstart_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='headstart_from',
            field=models.ManyToManyField(blank=True, help_text='Episodes which should grant a headstart for this episode', related_name='_episode_headstart_from_+', to='hunts.Episode'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='headstart_granted',
            field=models.DurationField(default=datetime.timedelta(0), help_text='How much headstart this puzzle gives to later episodes which gain headstart from this episode'),
        ),
    ]
