# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0029_auto_20170717_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='prereqs',
            field=models.ManyToManyField(related_name='_episode_prereqs_+', to='hunts.Episode'),
        ),
    ]
