# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0027_userpuzzledata_token'),
        ('hunts', '0029_auto_20170717_0109'),
    ]

    operations = [
    ]
