# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0030_episode_prereqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='episode',
            name='prequels',
            field=models.ManyToManyField(help_text='Set of episodes which must be completed before starting this one', related_name='_episode_prequels_+', to='hunts.Episode'),
        ),
    ]
