# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0031_auto_20170721_1324'),
        ('hunts', '0033_auto_20170721_0919'),
    ]

    operations = [
    ]
