# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0035_auto_20170722_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.Answer')),
                ('guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.Guess')),
            ],
        ),
        migrations.AddField(
            model_name='guess',
            name='validations',
            field=models.ManyToManyField(blank=True, through='hunts.GuessValidation', to='hunts.Answer'),
        ),
    ]
