# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
from enumfields import Enum

import hunts.models

class AnnoucmentType(Enum):
    INFO = 'I'
    SUCCESS = 'S'
    WARNING = 'W'
    ERROR = 'E'

class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0036_annoucement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hunts.Puzzle'),
        ),
        migrations.AlterField(
            model_name='annoucement',
            name='type',
            field=enumfields.fields.EnumField(default='I', enum=AnnoucmentType, max_length=1),
        ),
    ]
