# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0036_auto_20170724_2247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guessvalidation',
            unique_together=set([('answer', 'guess')]),
        ),
    ]
