# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0037_auto_20170725_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='correct_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hunts.Answer'),
        ),
    ]
