# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0037_auto_20170725_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='flavour',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='flavour',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
