# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:22
from __future__ import unicode_literals

from django.db import migrations


def generate_team(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    def get_team(guess):
        event = guess.for_puzzle.episode_set.get().event
        return Team.objects.filter(at_event=event, members=guess.by).get()

    Guess = apps.get_model('hunts', 'Guess')
    for g in Guess.objects.all():
        g.by_team = get_team(g)
        g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20170425_1400'),
        ('hunts', '0039_guess_by_team'),
    ]

    operations = [
        migrations.RunPython(generate_team, reverse_code=migrations.RunPython.noop),
    ]
