# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0041_guess_by_team_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='correct_current',
            field=models.BooleanField(default=False),
        ),
    ]
