# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0042_guess_correct_current'),
        ('hunts', '0038_auto_20170728_1637'),
    ]

    operations = [
    ]
