# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0043_merge_20170731_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='by_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team'),
        ),
    ]
