# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0044_auto_20170802_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamdata',
            options={'verbose_name_plural': 'Team data'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User data'},
        ),
    ]
