# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_max_team_size'),
        ('hunts', '0044_auto_20170802_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('file', models.FileField(upload_to='events/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='puzzlefile',
            unique_together=set([('puzzle', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='huntfile',
            unique_together=set([('event', 'slug')]),
        ),
    ]
