# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0045_auto_20170802_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='huntfile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='huntfile',
            name='event',
        ),
        migrations.DeleteModel(
            name='HuntFile',
        ),
    ]
