# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0046_auto_20170804_0029'),
        ('hunts', '0045_auto_20170802_2340'),
    ]

    operations = [
    ]
