# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0047_merge_20170804_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='flavour',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='flavour',
            field=models.TextField(blank=True),
        ),
    ]
