# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import hunts.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170804_0029'),
        ('hunts', '0048_auto_20170804_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('type', enumfields.fields.EnumField(default='I', enum=hunts.models.AnnouncementType, max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.Event')),
                ('puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hunts.Puzzle')),
            ],
        ),
        migrations.RemoveField(
            model_name='annoucement',
            name='event',
        ),
        migrations.RemoveField(
            model_name='annoucement',
            name='puzzle',
        ),
        migrations.DeleteModel(
            name='Annoucement',
        ),
    ]
