# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0049_auto_20170808_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='cb_content',
            field=models.TextField(blank=True, default='', verbose_name='Callback content'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='cb_runtime',
            field=models.CharField(choices=[('I', 'IFrame Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime'), ('S', 'Static Runtime')], default='S', help_text='Runtime for responding to an AJAX callback for this question, should return JSON', max_length=1, verbose_name='Callback runtime'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='flavour',
            field=models.TextField(blank=True, help_text='Separate flavour text for the puzzle. Should not be required for solving the puzzle', verbose_name='Flavour text'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='runtime',
            field=models.CharField(choices=[('I', 'IFrame Runtime'), ('L', 'Lua Runtime'), ('R', 'Regex Runtime'), ('S', 'Static Runtime')], default='S', help_text='Runtime for generating the question content', max_length=1),
        ),
    ]
