# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import hunts.models
import re


def migrate_puzzle_files(apps, schema_editor):
    PuzzleFile = apps.get_model('hunts', 'PuzzleFile')
    for puzzle_file in PuzzleFile.objects.all():
        puzzle_file.file = re.sub(r"^puzzles/", "puzzles/{0}/".format(puzzle_file.puzzle.id), str(puzzle_file.file))
        puzzle_file.save()


def revert_puzzle_files(apps, schema_editor):
    PuzzleFile = apps.get_model('hunts', 'PuzzleFile')
    for puzzle_file in PuzzleFile.objects.all():
        puzzle_file.file = re.sub(r"^puzzles/\d+/", "puzzles/", str(puzzle_file.file))
        puzzle_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0049_auto_20170808_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlefile',
            name='file',
            field=models.FileField(upload_to=hunts.models.puzzle_file_path),
        ),
        migrations.RunPython(migrate_puzzle_files, reverse_code=revert_puzzle_files),
    ]
