# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0050_auto_20170813_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='text',
            field=models.TextField(help_text='Text displayed when this clue is unlocked'),
        ),
        migrations.AlterField(
            model_name='puzzlefile',
            name='slug',
            field=models.SlugField(help_text='Precede the slug with a $ in the puzzle content to insert the URL of the file.'),
        ),
        migrations.AlterField(
            model_name='unlock',
            name='text',
            field=models.TextField(help_text='Text displayed when this clue is unlocked'),
        ),
    ]
