# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0052_auto_20170814_0007'),
        ('hunts', '0050_auto_20170813_2236'),
    ]

    operations = [
    ]
