# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:58
from __future__ import unicode_literals

from django.db import migrations
import os
import shutil


def migrate_puzzle_files(apps, schema_editor):
    PuzzleFile = apps.get_model('hunts', 'PuzzleFile')
    for puzzle_file in PuzzleFile.objects.all():
        old_file = os.path.join('/uploads/puzzles', os.path.basename(puzzle_file.file.path))
        try:
            shutil.move(old_file, puzzle_file.file.path)
        except FileNotFoundError:
            pass

def revert_puzzle_files(apps, schema_editor):
    PuzzleFile = apps.get_model('hunts', 'PuzzleFile')
    for puzzle_file in PuzzleFile.objects.all():
        old_file = os.path.join('/uploads/puzzles', os.path.basename(puzzle_file.file.path))
        try:
            shutil.move(puzzle_file.file.path, old_file)
        except FileNotFoundError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0053_merge_20170814_0040'),
    ]

    operations = [
        migrations.RunPython(migrate_puzzle_files, reverse_code=revert_puzzle_files),
    ]
