# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_examples_text'),
        ('teams', '0006_merge_20170802_2329'),
        ('hunts', '0055_auto_20170814_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='teampuzzledata',
            unique_together=set([('puzzle', 'team')]),
        ),
        migrations.AlterUniqueTogether(
            name='userdata',
            unique_together=set([('event', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='userpuzzledata',
            unique_together=set([('puzzle', 'user')]),
        ),
    ]
