# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0056_auto_20170826_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
