# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0057_auto_20170829_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzlefile',
            name='slug',
            field=models.CharField(help_text='Include the URL of the file in puzzle content using $slug or ${slug}.', max_length=50),
        ),
    ]
