# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0059_auto_20180408_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='parallel',
            field=models.BooleanField(default=False, help_text='Allow players to answer riddles in this episode in any order they like'),
        ),
    ]
