# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
