# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ihunt', '0005_auto_20160318_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.AlterField(
            model_name='puzzleset',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzlesets', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='at_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.Event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
