# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihunt', '0008_auto_20170110_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
            preserve_default=False,
        ),
    ]
