# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihunt', '0012_auto_20170225_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='runtime',
            field=models.CharField(choices=[('S', 'Static Runtime'), ('L', 'Lua Runtime')], default='S', max_length=1),
        ),
    ]
