# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 12:50
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Min


def migrate_seat(apps, schema_editor):
    Attendance = apps.get_model('accounts', 'Attendance')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in UserProfile.objects.all():
        for team in user.teams.annotate(Min('at_event__episode__start_date')).order_by('at_event__episode__start_date__min'):
            attendance = Attendance(event=team.at_event, user=user, seat='')
            attendance.save()
        attendance.seat = user.seat
        attendance.save()


def revert_seat(apps, schema_editor):
    Attendance = apps.get_model('accounts', 'Attendance')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for user in UserProfile.objects.all():
        attendance = user.attendance_set.annotate(Min('event__episode__start_date')).order_by('-at_event__episode__start_date__min').first()
        user.seat = attendance.seat
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_attendance'),
    ]

    operations = [
        migrations.RunPython(migrate_seat, reverse_code=revert_seat),
    ]
